shopItems:
  Battery shop:
    - name: "Battery"
      description: "BYD dual-panel LiFePo4 battery"
      size: "SMALL"
      price: 36375
      capacity: 5.12
    - name: "Battery"
      description: "BYD penta-panel LiFePo4 battery"
      size: "MEDIUM"
      price: 81250
      capacity: 12.8
    - name: "Battery"
      description: "BYD octa-panel LiFePo4 battery"
      size: "LARGE"
      price: 127250
      capacity: 22.1
  Fossil energyshop: # Estimated energy prices, due to lack of sources
    - name: "Coal"
      description: "Energy from 1kg coal"
      size: "MEDIUM"
      price: 1.28
      emission: 2.4 # kg co2
      output: 90 # kwh
    - name: "Oil"
      description: "It is energy from oil"
      size: "MEDIUM"
      price: 13.3
      emission: 3.1
      output: 151
    - name: "Natural gas"
      description: "It is energy from natural gas"
      size: "MEDIUM"
      price: 1.83
      emission: 2.7
      output: 176
  Solar shop:
    - name: "Solar Energy"
      description: "Photovoltaic solar panel array of 13sqm"
      size: "SMALL"
      price: 2023
      emission: 0
      output: 169.76
      textureURL: "/images/LilleSolcelle.png"
    - name: "Solar Energy"
      description: "Photovoltaic solar panel array of 32sqm"
      size: "MEDIUM"
      price: 52000
      emission: 0
      output: 5926
      textureURL: "/images/MellemSolcelle.png"
    - name: "Solar Energy"
      description: "Photovoltaic solar panel array of 65sqm"
      size: "LARGE"
      price: 91579
      emission: 0
      output: 12033
      textureURL: "/images/StoreSolcelle.png"
  Windturbine shop:
    - name: "Wind Energy"
      description: "Gaia 10kW wind turbine"
      size: "SMALL"
      price: 73557
      emission: 0
      output: 32000
    - name: "Wind Energy"
      description: "Power 20kW wind generator"
      size: "MEDIUM"
      price: 163460
      emission: 0
      output: 122640
