shopItems:
  Battery shop:
    - name: "Battery"
      description: "BYD dual-panel LiFePo4 battery"
      size: "SMALL"
      price: 36375
      capacity: 5.12
      textureURL: "/images/Lille batteri.png"
      width: 1
      height: 1
    - name: "Battery"
      description: "BYD penta-panel LiFePo4 battery"
      size: "MEDIUM"
      price: 81250
      capacity: 12.8
      textureURL: "/images/Mellem Batteri.png"
      width: 2
      height: 1
    - name: "Battery"
      description: "BYD octa-panel LiFePo4 battery"
      size: "LARGE"
      price: 127250
      capacity: 22.1
      textureURL: "/images/Stor batteri.png"
      width: 3
      height: 1
  Fossil energyshop: # Estimated energy prices, due to lack of sources
    - name: "Coal"
      description: "Energy from coal"
      size: "MEDIUM"
      price: 240.28
      emission: 18.4 # kg co2
      output: 90 # kwh
      thumbImageURL: "/images/Kul.png"
    - name: "Oil"
      description: "Energy from oil"
      size: "MEDIUM"
      price: 300.6
      emission: 25.1
      output: 123
      thumbImageURL: "/images/Olie.png"
    - name: "Natural gas"
      description: "Energy from natural gas"
      size: "MEDIUM"
      price: 224.5
      emission: 15.7
      output: 76
      thumbImageURL: "/images/Gas.png"
  Solar shop:
    - name: "Solar Energy"
      description: "Photovoltaic solar panel array of 13sqm"
      size: "SMALL"
      price: 10150
      emission: 0
      output: 1232
      textureURL: "/images/LilleSolcelle.png"
      width: 1
      height: 1
    - name: "Solar Energy"
      description: "Photovoltaic solar panel array of 32sqm"
      size: "MEDIUM"
      price: 52000
      emission: 0
      output: 5926
      textureURL: "/images/MellemSolcelle.png"
      width: 2
      height: 1
    - name: "Solar Energy"
      description: "Photovoltaic solar panel array of 65sqm"
      size: "LARGE"
      price: 91579
      emission: 0
      output: 12033
      textureURL: "/images/StoreSolcelle.png"
      width: 3
      height: 1
  Windturbine shop:
    - name: "Wind Energy"
      description: "Gaia 10kW wind turbine"
      size: "SMALL"
      price: 73557
      emission: 0
      output: 32000
      textureURL: "/images/Lille Moelle Stativ.png"
      width: 1
      height: 3
      thumbImageURL: "/images/Lille moelle.png"
    - name: "Wind Energy"
      description: "Power 20kW wind generator"
      size: "MEDIUM"
      price: 163460
      emission: 0
      output: 122640
      textureURL: "/images/Stor moelle stativ.png"
      width: 1
      height: 5
      thumbImageURL: "/images/Store moelle.png"
