@startuml
Actor Player as player
player -> Game: Executes //buy <item-id>//
activate Game
Game -> Shop: Request item by id
activate Shop
Shop --> Game: Return item reference or null
deactivate Shop

Game -> Player: Withdraw money
Player --> Game: Withdrawal status

alt Player couldn't afford item
    Game -> Game: Cancel purchase
    else Item //instanceof// ""EnergySource""
    Game->BuildArea: Add energysource to buildarea
    else Item //instanceof// ""EnergyConsumer""
    Game->House: Add energyconsumer to house
    else Otherwise
    Game->Player: Purchase failed, redeposit money
end

Game -> player: Print purchase status


deactivate Game

alt Not located in shop
    Game->player: Prints //...not in a shop.//
    else No second word
    Game->player: Prints //Buy what?//
end

@enduml